const countryCities = {
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Miami"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Liverpool"],
  "Turkey": ["Istanbul", "Ankara", "Izmir", "Antalya", "Bursa"],
  "Germany": ["Berlin", "Munich", "Hamburg", "Frankfurt"],
  "Canada": ["Toronto", "Vancouver", "Montreal", "Calgary"],
  "France": ["Paris", "Marseille", "Lyon", "Nice"],
  "Italy": ["Rome", "Milan", "Naples", "Turin"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville"],
  "Netherlands": ["Amsterdam", "Rotterdam", "Utrecht", "Eindhoven"],
  "Belgium": ["Brussels", "Antwerp", "Ghent", "Bruges"],
  "Austria": ["Vienna", "Graz", "Linz", "Salzburg"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Bern"],
  "Poland": ["Warsaw", "Kraków", "Wrocław", "Gdańsk"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzeň"],
  "Hungary": ["Budapest", "Debrecen", "Szeged", "Miskolc"],
  "Romania": ["Bucharest", "Cluj-Napoca", "Timișoara", "Iași"],
  "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmö", "Uppsala"],
  "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger"],
  "Finland": ["Helsinki", "Espoo", "Tampere", "Oulu"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg"],
  "Ireland": ["Dublin", "Cork", "Galway", "Limerick"],
  "Portugal": ["Lisbon", "Porto", "Braga", "Coimbra"],
  "Brazil": ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"],
  "Argentina": ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"],
  "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla"],
  "Chile": ["Santiago", "Valparaíso", "Concepción", "La Serena"],
  "Colombia": ["Bogotá", "Medellín", "Cali", "Barranquilla"],
  "Peru": ["Lima", "Arequipa", "Cusco", "Trujillo"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria"],
  "Egypt": ["Cairo", "Alexandria", "Giza", "Luxor"],
  "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Beersheba"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina"],
  "UAE": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Chennai"],
  "Pakistan": ["Karachi", "Lahore", "Islamabad", "Rawalpindi"],
  "China": ["Beijing", "Shanghai", "Shenzhen", "Guangzhou"],
  "Japan": ["Tokyo", "Osaka", "Kyoto", "Yokohama"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu"],
  "Thailand": ["Bangkok", "Chiang Mai", "Phuket", "Pattaya"],
  "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan"],
  "Malaysia": ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh"],
  "Philippines": ["Manila", "Cebu City", "Davao City", "Quezon City"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton"],

  "Other": []
};

export default countryCities;
